batch_size: 10
input_dim: 5
frontier_size: 1
max_tree_depth: 8
num_iterations: 100000
gamma: 0.96
rollout_length: 16
lam: 0.97
vf_coef: 0.1
learning_rate: 3e-5
tree_lr: 3e-5
num_br_updates: 1
eval_every: 100
do_self_play: False
br_entropy_beta: 0.007
agent_entropy_beta: 0.007

mlp:
  # for the first MLP
  num_layers: 2
  features: 64

gru:
  hidden_dim: 64

output_mlp:
  # for the final MLP
  num_layers: 1
  features: 64